### ISSUE TITLE
Set up APT repository on S3 for Medplum packages

### ISSUE THREAD

**Issue by codyebberson** [medplum/medplum#5480]
We should set up an APT repository hosted on S3/CloudFront to distribute our Debian packages. This will enable users to install and update Medplum using standard APT tools.

## Infrastructure Setup

1. Create S3 bucket `apt.medplum.com`
   - Enable public access (for package downloads)
   - Configure bucket policy for CloudFront access

2. Create CloudFront distribution
   - Origin: apt.medplum.com S3 bucket
   - Configure CNAME: apt.medplum.com
   - Enable compression

3. Set up DNS
   - Create CNAME record for apt.medplum.com pointing to CloudFront distribution

## GPG Setup

1. Create GPG key for package signing:

```bash
gpg --full-generate-key  # Use RSA, 4096 bits
gpg --list-secret-keys  # Note the key ID
gpg --armor --export KEY_ID > medplum-archive-keyring.gpg
```

2. Add GPG key to GitHub repository secrets:
   - Export private key: `gpg --export-secret-keys -a KEY_ID`
   - Add as secret: `MEDPLUM_GPG_KEY`
   - Add passphrase as secret: `MEDPLUM_GPG_PASSPHRASE`

## GitHub Actions Workflow

Create `.github/workflows/apt-repo.yml`:

```yaml
name: Update APT Repository

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install deb-s3
        run: gem install deb-s3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Import GPG key
        run: |
          echo "${{ secrets.MEDPLUM_GPG_KEY }}" | gpg --import
          echo "${{ secrets.MEDPLUM_GPG_PASSPHRASE }}" | gpg --passphrase-fd 0 --pinentry-mode loopback -u KEY_ID --yes --sign test.txt

      - name: Build package
        run: |
          # Package build steps here
          # This should create medplum_*.deb

      - name: Upload to APT repository
        run: |
          deb-s3 upload \
            --bucket apt.medplum.com \
            --prefix ubuntu \
            --codename $(lsb_release -cs) \
            --sign=${{ secrets.MEDPLUM_GPG_KEY_ID }} \
            --gpg-options="--passphrase-fd 0 --pinentry-mode loopback" \
            --preserve-versions \
            medplum_*.deb \
            < <(echo "${{ secrets.MEDPLUM_GPG_PASSPHRASE }}")
```

## User Installation Instructions

After setup is complete, users will be able to install Medplum using:

```bash
# Add Medplum repository
curl -fsSL https://apt.medplum.com/medplum-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/medplum-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/medplum-archive-keyring.gpg] https://apt.medplum.com stable main" | sudo tee /etc/apt/sources.list.d/medplum.list

# Install Medplum
sudo apt update
sudo apt install medplum
```

## Testing Checklist

- [ ] S3 bucket and CloudFront are properly configured
- [ ] GPG key generation and GitHub secrets setup
- [ ] GitHub Actions workflow successfully builds and uploads package
- [ ] Package can be downloaded via CloudFront
- [ ] Installation instructions work on a fresh Ubuntu system
- [ ] Package updates are detected by `apt update`

## Security Considerations

- Ensure S3 bucket policy only allows necessary access
- Protect GPG keys and passphrases
- Use separate AWS credentials for package uploads
- Consider implementing package signing verification
- Monitor CloudFront access logs for abuse

## References

- [deb-s3 Documentation](https://github.com/deb-s3/deb-s3)
- [Debian Repository Format](https://wiki.debian.org/DebianRepository/Format)
- [APT Repository Setup Guide](https://wiki.debian.org/DebianRepository/Setup)
