### ISSUE TITLE
Cannot Configure Server via Environment Variables in medplum/medplum-app:4.1

### ISSUE THREAD

**Issue by Fede-Berga** [medplum/medplum#6544]
I cannot see the way to specify the backend server URL in the The Docker Medplum App image [medplum/medplum-app:4.1](https://hub.docker.com/r/medplum/medplum-app). Can somebody help me doing that?

**Comment by ThatOneBro** [comment]
@Fede-Berga Hi, sorry about that. We should definitely get this documented some more.

Setting `MEDPLUM_BASE_URL` to the base URL you want, for example:
`MEDPLUM_BASE_URL=https://example.com/` should be what you're looking for

**Comment by chas523** [comment]
Hi there,

I experienced the same problem when trying to run my app via Docker. The Medplum app always uses a fixed URL and fetches from localhost:8103, but in my self-hosted solution, the API is on a different address.

To set up the backend server URL for the Medplum app, you need to configure the environment variables. For example:

```yml
  # Medplum app container (web UI)
  medplum-app:
    image: medplum/medplum-app:latest
    restart: always
    depends_on:
      medplum-server:
        condition: service_healthy
    ports:
      - '3000:3000'
    environment:
      MEDPLUM_BASE_URL: 'http://example:8103/'
      MEDPLUM_CLIENT_ID: ''
      GOOGLE_CLIENT_ID: ''
      RECAPTCHA_SITE_KEY: '6LfHdsYdAAAAAC0uLnnRrDrhcXnziiUwKd8VtLNq'
      MEDPLUM_REGISTER_ENABLED: 'true'
      MEDPLUM_AWS_TEXTRACT_ENABLED: 'false'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000']
      interval: 10s
      timeout: 5s
      retries: 5

```
